<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template name="site-footer">
    <footer xmlns="http://www.w3.org/1999/xhtml" id="footer" class="site-footer">
      <div class="site-footer-content">
        Site crafted with ❤️ , <a href="https://getbootstrap.com/">Bootstrap</a> and GPT-5,
        generated by <a href="https://jaspervdj.be/hakyll/">Hakyll</a>, and
        hosted on <a href="https://pages.github.com">GitHub Pages</a>.
      </div>
    </footer>
  </xsl:template>
</xsl:stylesheet>
