language: haskell
cabal: "2.4"
ghc: 
  - "8.6.5"
cache:
  directories:
    - $HOME/.cabal
install:
  - cabal new-install hakyll --flags="-previewServer -watchServer"
  - ghc --make site.hs
script:
  - ./site build
deploy:
  provider: pages
  local_dir: "_site/"
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: source
  keep_history: true
