dist: bionic
notifications:
  email: false
language: haskell
ghc: 
  - "8.4.4"
cache:
  directories:
    - $HOME/.stack
before_install:
# Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        
install:
  - stack build --system-ghc
script:
  - stack exec site build
deploy:
  provider: pages
  local_dir: "_site/"
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: source
  keep_history: true
