dist: bionic
branches:
  only:
    - source
notifications:
  email: false
language: c
matrix:
  include:
      addons:
        apt: 
          packages:
            - ghc
            - libghc-hakyll-dev
install:
  - ghc --make site.hs
script:
  - ./site build
deploy:
  provider: pages
  local_dir: "_site/"
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: source
  keep_history: true
