name: L-TChen-github-io
version: 0.1.0.0
github: L-TChen/L-TChen.github.io

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.14 && < 5
  - bytestring
  - containers
  - directory
  - filepath
  - hakyll
  - hakyll-sass
  - pandoc
  - text
  - time
  - xml-conduit

executables:
  site:
    main: site.hs
    source-dirs:
      - src
    other-modules:
      - BibTeX
      - Forester
      - Publications
      - SummerInterns
    ghc-options:
      - -threaded

tests:
  forester-spec:
    main: ForesterSpec.hs
    source-dirs:
      - test
      - src
    other-modules:
      - Forester
    dependencies:
      - hspec
