name: Hakyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.10.4' ]
    env:
      FLAGS: "--flag hakyll:-previewServer --flag hakyll:-watchServer --flag hakyll:-checkexternal"

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-no-global: true
        stack-version: 'latest'

    - name: Cache ~/.stack and .stack-work
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.stack
          .stack-work
        key: stack-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock') }}

    - name: Build dependencies and the site generator
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: |
        stack build ${FLAGS}
        npm install

    - name: Build the site
      env:
        LANG: en_US.UTF-8
      run: |
        stack build ${FLAGS} --exec "site build"

    - name: Check the site output
      run: |
        stack build ${FLAGS} --exec "site check --internal-links"

    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/source'
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: _site
        publish_branch: master
        force_orphan: true
