name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-${{ env.GHC_VERSION }}-
          cabal-store-${{ runner.OS }}-
    - name: Build dependencies and the site generator
      run: |
        cabal update
        cabal install hakyll --lib --flags="-previewServer -watchServer"
        cabal build
        #    - name: Build the site
        #      env:
        #        LANG=en_US.UTF-8
        #      run: |
        #        cabal exec -- site build
    - uses: peaceiris/actions-gh-pages@v2.10.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: _site
        if: github.ref == 'refs/heads/source'
